/*Add to LocalStorage JSON for emulation AJAX*/
$(function () {
    var data = {
        "data": [
            [
                "Vojager",
                "Official",
                "Edinburgh",
                "61",
                "$320,800"
            ],
                [
                "drifter",
                    "sport",
                    "Tokyo",
                    "8422",
                    "$170,750"
                ],
            [
                "Jumper",
                "Youth",
                "San Francisco",
                "1562",
                "$86,000"
            ],
            [
                "Gentleman",
                "Business",
                "Edinburgh",
                "6224",
                "$433,060"
            ],
            [
                "drifter",
                "sport",
                "Tokyo",
                "5407",
                "$162,700"
            ],
            [
                "Jumper",
                "Youth",
                "New York",
                "4804",
                "$372,000"
            ],
            [
                "drifter",
                "sport",
                "San Francisco",
                "9608",
                "$137,500"
            ],
            [
                "Vojager",
                "Official",
                "Tokyo",
                "6200",
                "$327,900"
            ],
            [
                "drifter",
                "sport",
                "San Francisco",
                "2360",
                "$205,500"
            ],
            [
                "drifter",
                "sport",
                "Edinburgh",
                "1667",
                "$103,600"
            ],
            [
                "Vojager",
                "Official",
                "London",
                "3814",
                "$90,560"
            ],
            [
                "Jumper",
                "Youth",
                "Edinburgh",
                "9497",
                "$342,000"
            ],
            [
                "Vojager",
                "Official",
                "San Francisco",
                "6741",
                "$470,600"
            ],
            [
                "drifter",
                "sport",
                "London",
                "3597",
                "$313,500"
            ],
            [
                "Gentleman",
                "Business",
                "London",
                "1965",
                "$385,750"
            ],
            [
                "drifter",
                "sport",
                "London",
                "1581",
                "$198,500"
            ],
            [
                "Vojager",
                "Official",
                "New York",
                "3059",
                "$725,000"
            ],
            [
                "Gentleman",
                "Business",
                "New York",
                "1721",
                "$237,500"
            ],
            [
                "drifter",
                "sport",
                "London",
                "2558",
                "$132,000"
            ],
            [
                "Vojager",
                "Official",
                "Edinburgh",
                "2290",
                "$217,500"
            ],
            [
                "drifter",
                "sport",
                "New York",
                "1937",
                "$345,000"
            ],
            [
                "Vojager",
                "Official",
                "New York",
                "6154",
                "$675,000"
            ],
            [
                "drifter",
                "sport",
                "New York",
                "8330",
                "$106,450"
            ],
            [
                "Jumper",
                "Youth",
                "Sidney",
                "3023",
                "$85,600"
            ],
            [
                "Vojager",
                "Official",
                "London",
                "5797",
                "$1,200,000"
            ],
            [
                "drifter",
                "sport",
                "Edinburgh",
                "8822",
                "$92,575"
            ],
            [
                "Vojager",
                "Official",
                "Singapore",
                "9239",
                "$357,650"
            ],
            [
                "Vojager",
                "Official",
                "Edinburgh",
                "61",
                "$320,800"
            ],
            [
                "drifter",
                "sport",
                "Tokyo",
                "8422",
                "$170,750"
            ],
            [
                "Jumper",
                "Youth",
                "San Francisco",
                "1562",
                "$86,000"
            ],
            [
                "Gentleman",
                "Business",
                "Edinburgh",
                "6224",
                "$433,060"
            ],
            [
                "drifter",
                "sport",
                "Tokyo",
                "5407",
                "$162,700"
            ],
            [
                "Jumper",
                "Youth",
                "New York",
                "4804",
                "$372,000"
            ],
            [
                "drifter",
                "sport",
                "San Francisco",
                "9608",
                "$137,500"
            ],
            [
                "Vojager",
                "Official",
                "Tokyo",
                "6200",
                "$327,900"
            ],
            [
                "drifter",
                "sport",
                "San Francisco",
                "2360",
                "$205,500"
            ],
            [
                "drifter",
                "sport",
                "Edinburgh",
                "1667",
                "$103,600"
            ],
            [
                "Vojager",
                "Official",
                "London",
                "3814",
                "$90,560"
            ],
            [
                "Jumper",
                "Youth",
                "Edinburgh",
                "9497",
                "$342,000"
            ],
            [
                "Vojager",
                "Official",
                "San Francisco",
                "6741",
                "$470,600"
            ],
            [
                "drifter",
                "sport",
                "London",
                "3597",
                "$313,500"
            ],
            [
                "Gentleman",
                "Business",
                "London",
                "1965",
                "$385,750"
            ],
            [
                "drifter",
                "sport",
                "London",
                "1581",
                "$198,500"
            ],
            [
                "Vojager",
                "Official",
                "New York",
                "3059",
                "$725,000"
            ],
            [
                "Gentleman",
                "Business",
                "New York",
                "1721",
                "$237,500"
            ],
            [
                "drifter",
                "sport",
                "London",
                "2558",
                "$132,000"
            ],
            [
                "Vojager",
                "Official",
                "Edinburgh",
                "2290",
                "$217,500"
            ],
            [
                "drifter",
                "sport",
                "New York",
                "1937",
                "$345,000"
            ],
            [
                "Vojager",
                "Official",
                "New York",
                "6154",
                "$675,000"
            ],
            [
                "drifter",
                "sport",
                "New York",
                "8330",
                "$106,450"
            ],
            [
                "Jumper",
                "Youth",
                "Sidney",
                "3023",
                "$85,600"
            ],
            [
                "Vojager",
                "Official",
                "London",
                "5797",
                "$1,200,000"
            ],
            [
                "drifter",
                "sport",
                "Edinburgh",
                "8822",
                "$92,575"
            ],
            [
                "Vojager",
                "Official",
                "Singapore",
                "9239",
                "$357,650"
            ]
        ]
    };

   localStorage.setItem("jsonTable", JSON.stringify(data) );
});